spring:
  datasource:
    url: jdbc:postgresql://localhost:5455/postgres?user=postgres&password=password
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
